use std::collections::HashMap;
use factorio_lib_rs_derive::DataTableAccessable;
use crate::prototypes::{PrototypeBaseSpec, Prototype, PrototypeBase, PrototypeType};
use super::additional_types::{Color, Sound, DaytimeColorLookupTable, Factorio2DVector, TriggerTargetMask, FileName, SimulationDefinition, BoxSpecification, Animation, Sprite};
use super::LocalisedString;

/// <https://wiki.factorio.com/Prototype/UtilityConstants>
#[derive(Debug, Prototype, PrototypeBase, DataTableAccessable)]
#[data_table(utility_constants)]
pub struct UtilityConstants {
    name: String,
    prototype_base: PrototypeBaseSpec,
    entity_button_background_color: Color,
    building_buildable_too_far_tint: Color,
    building_buildable_tint: Color,
    building_not_buildable_tint: Color,
    building_ignorable_tint: Color,
    building_no_tint: Color,
    ghost_tint: Color,
    tile_ghost_tint: Color,
    equipment_default_background_color: Color,
    equipment_default_background_border_color: Color,
    equipment_default_grabbed_background_color: Color,
    turret_range_visualization_color: Color,
    capsule_range_visualization_color: Color,
    artillery_range_visualization_color: Color,
    train_no_path_color: Color,
    train_destination_full_color: Color,
    chart: UtiliyConstantsChart,
    default_player_force_color: Color,
    item_outline_radiusdefault_enemy_force_color: Color,
    default_other_force_color: Color,
    deconstruct_mark_tint: Color,
    rail_planner_count_button_color: Color,
    count_button_size: i32,
    zoom_to_world_can_use_nightvision: bool,
    zoom_to_world_effect_strength: f32,
    max_terrain_building_size: u8,
    small_area_size: f32,
    medium_area_size: f32,
    small_blueprint_area_size: f32,
    medium_blueprint_area_size: f32,
    enabled_recipe_slot_tint: Color,
    disabled_recipe_slot_tint: Color,
    disabled_recipe_slot_background_tint: Color,
    forced_enabled_recipe_slot_background_tint: Color,
    rail_segment_colors: Vec<Color>,
    player_colors: Vec<UtilityConstantsPlayerColor>, // item with `name` == default must exist and be the first item in array
    server_command_console_chat_color: Color,
    script_command_console_chat_color: Color,
    default_alert_icon_scale: f32,
    default_alert_icon_shift_by_type: Option<HashMap<String, Factorio2DVector>>,
    default_alert_icon_scale_by_type: Option<HashMap<String, f32>>,
    daytime_color_lookup: DaytimeColorLookupTable,
    zoom_to_world_daytime_color_lookup: DaytimeColorLookupTable,
    checkerboard_white: Color,
    checkerboard_black: Color,
    item_outline_color: Color,
    item_outline_radius: f32,
    item_outline_inset: f32,
    item_outline_sharpness: f32,
    filter_outline_color: Color,
    icon_shadow_radius: f32,
    icon_shadow_inset: f32,
    icon_shadow_sharpness: f32,
    icon_shadow_color: Color,
    clipboard_history_size: u32,
    recipe_step_limit: u32,
    manual_rail_building_reach_modifier: f64,
    train_temporary_stop_wait_time: u32,
    train_time_wait_condition_default: u32,
    train_inactivity_wait_condition_default: u32,
    default_trigger_target_mask_by_type: Option<HashMap<String, TriggerTargetMask>>,
    unit_group_pathfind_resolution: i8,
    unit_group_max_pursue_distance: f64,
    dynamic_recipe_overload_factor: f64,
    minimum_recipe_overload_multiplier: u32,
    maximum_recipe_overload_multiplier: u32,
    tree_leaf_distortion_strength_far: Factorio2DVector,
    tree_leaf_distortion_distortion_far: Factorio2DVector,
    tree_leaf_distortion_speed_far: Factorio2DVector,
    tree_leaf_distortion_strength_near: Factorio2DVector,
    tree_leaf_distortion_distortion_near: Factorio2DVector,
    tree_leaf_distortion_speed_near: Factorio2DVector,
    tree_shadow_roughness: f32,
    tree_shadow_speed: f32,
    missing_preview_sprite_location: FileName,
    main_menu_background_image_location: FileName,
    main_menu_simulations: HashMap<String, SimulationDefinition>,
    main_menu_background_vignette_intensity: f32,
    main_menu_background_vignette_sharpness: f32,
    default_scorch_mark_color: Color,
    train_button_hovered_tint: Color,
    select_group_row_count: u32, // Range: [1, 100]
    select_slot_row_count: u32, // Range: [1, 100]
    inventory_width: u32, // Range: [1, 100]
    module_inventory_width: u32, // Range: [1, 100]
    tooltip_monitor_edge_border: i32, // Must be >= 1
    normalised_achievement_icon_size: u32, // Must be >= 1
    tutorial_notice_icon_size: u32, // Must be >= 1
    flying_text_ttl: u32, // Must be >= 1
    bonus_gui_ordering: HashMap<String, String>,
    train_path_finding: UtilityConstantsTrainPathFinding,
    map_editor: UtilityConstantsMapEditor,
    color_filters: Vec<UtilityConstantColorFilter>,
    entity_renderer_search_box_limits: UtilityConstantsEntityRendererSerahcBoxLimits,
    light_renderer_search_distance_limit: u8
}

#[derive(Debug)]
pub struct UtiliyConstantsChart {
    electric_lines_color: Color,
    electric_lines_color_switch_enabled: Color,
    electric_lines_color_switch_disabled: Color,
    electric_power_pole_color: Color,
    switch_color: Color,
    electric_line_width: f64,
    electric_line_minimum_absolute_width: f64,
    turret_range_color: Color,
    artillery_range_color: Color,
    pollution_color: Color,
    default_friendly_color: Color,
    default_enemy_color: Color,
    rail_color: Color,
    entity_ghost_color: Color,
    vehicle_outer_color: Color,
    vehicle_outer_color_selected: Color,
    vehicle_inner_color: Color,
    vehicle_wagon_connection_color: Color,
    resource_outline_selection_color: Color,
    chart_train_stop_text_color: Color,
    chart_train_stop_disabled_text_color: Color,
    chart_train_stop_full_text_color: Color,
    red_signal_color: Color,
    green_signal_color: Color,
    blue_signal_color: Color,
    yellow_signal_color: Color,
    chart_deconstruct_tint: Color,
    default_friendly_color_by_type: Option<HashMap<String, Color>>,
    default_color_by_type: Option<HashMap<String, Color>>,
    explosion_visualization_duration: u32,
    train_path_color: Color,
    train_preview_path_outline_color: Color,
    train_current_path_outline_color: Color,
    custom_tag_scale: f32, // Default: 0.6
    custom_tag_selected_overlay_tint: Color
}

#[derive(Debug)]
pub struct UtilityConstantsPlayerColor {
    name: String,
    player_color: Color,
    chat_color: Color
}

#[derive(Debug)]
pub struct UtilityConstantsTrainPathFinding {
    train_stop_penalty: u32,
    stopped_manually_controlled_train_penalty: u32,
    stopped_manually_controlled_train_without_passenger_penalty: u32,
    signal_reserved_by_circuit_network_penalty: u32,
    train_in_station_penalty: u32,
    train_in_station_with_no_other_valid_stops_in_schedule: u32,
    train_arriving_to_station_penalty: u32,
    train_arriving_to_signal_penalty: u32,
    train_waiting_at_signal_penalty: u32,
    train_waiting_at_signal_tick_multiplier_penalty: f32, // Must be >= 0
    train_with_no_path_penalty: u32,
    train_auto_without_schedule_penalty: u32
}

#[derive(Debug)]
pub struct UtilityConstantsMapEditor {
    clone_editor_copy_source_color: Color,
    clone_editor_copy_destination_allowed_color: Color,
    clone_editor_copy_destination_not_allowed_color: Color,
    clone_editor_brush_source_color: Color,
    clone_editor_brush_destination_color: Color,
    clone_editor_brush_cursor_preview_tint: Color,
    clone_editor_brush_world_preview_tint: Color,
    script_editor_select_area_color: Color,
    script_editor_drag_area_color: Color,
    force_editor_select_area_color: Color,
    cliff_editor_remove_cliffs_color: Color,
    tile_editor_selection_preview_tint: Color,
    tile_editor_area_selection_color: Color,
    decorative_editor_selection_preview_tint: Color,
    tile_editor_selection_preview_radius: u8,
    decorative_editor_selection_preview_radius: u8
}

#[derive(Debug)]
pub struct UtilityConstantColorFilter {
    name: String,
    localised_name: LocalisedString,
    matrix: [[f32; 4]; 4]
}

#[derive(Debug)]
pub struct UtilityConstantsEntityRendererSerahcBoxLimits {
    left: u8, // Range [6, 15]
    top: u8, // Range [3, 15]
    right: u8, // Range [3, 15]
    bottom: u8, // Range [4, 15]
}

/// <https://wiki.factorio.com/Prototype/UtilitySounds>
#[derive(Debug, Prototype, PrototypeBase, DataTableAccessable)]
#[data_table(utility_sounds)]
pub struct UtilitySounds {
    name: String,
    prototype_base: PrototypeBaseSpec,
    gui_click: Sound,
    list_box_click: Sound,
    build_small: Sound,
    build_medium: Sound,
    build_large: Sound,
    cannot_build: Sound,
    build_blueprint_small: Sound,
    build_blueprint_medium: Sound,
    build_blueprint_large: Sound,
    deconstruct_small: Sound,
    deconstruct_medium: Sound,
    deconstruct_big: Sound,
    deconstruct_robot: Sound,
    rotated_small: Sound,
    rotated_medium: Sound,
    rotated_big: Sound,
    axe_mining_ore: Sound,
    mining_wood: Sound,
    axe_fighting: Sound,
    alert_destroyed: Sound,
    console_message: Sound,
    scenario_message: Sound,
    new_objective: Sound,
    game_lost: Sound,
    game_won: Sound,
    metal_walking_sound: Sound,
    research_completed: Sound,
    default_manual_repair: Sound,
    crafting_finished: Sound,
    inventory_click: Sound,
    inventory_move: Sound,
    clear_cursor: Sound,
    armor_insert: Sound,
    armor_remove: Sound,
    achievement_unlocked: Sound,
    wire_connect_pole: Sound,
    wire_disconnect: Sound,
    wire_pickup: Sound,
    tutorial_notice: Sound,
    smart_pipette: Sound,
    switch_gun: Sound,
    picked_up_item: Sound,
    blueprint_selection_ended: Sound,
    blueprint_selection_started: Sound,
    deconstruction_selection_started: Sound,
    deconstruction_selection_ended: Sound,
    cancel_deconstruction_selection_started: Sound,
    cancel_deconstruction_selection_ended: Sound,
    upgrade_selection_started: Sound,
    upgrade_selection_ended: Sound,
    copy_activated: Sound,
    cut_activated: Sound,
    paste_activated: Sound,
    item_deleted: Sound,
    entity_settings_pasted: Sound,
    entity_settings_copied: Sound,
    item_spawned: Sound,
    confirm: Sound,
    undo: Sound,
    drop_item: Sound,
    rail_plan_start: Sound
}

/// <https://wiki.factorio.com/Prototype/UtilitySprites>
#[derive(Debug, Prototype, PrototypeBase, DataTableAccessable)]
#[data_table(utility_sprites)]
pub struct UtilitySprites {
    // Only one instance allowed
    name: String,
    prototype_base: PrototypeBaseSpec,
    cursor_box: UtilitySpritesCursorBox,
    clouds: Animation,
    arrow_button: Animation,
    explosion_chart_visualization: Animation,
    refresh_white: Animation,
    center: Sprite,
    check_mark: Sprite,
    check_mark_white: Sprite,
    check_mark_green: Sprite,
    check_mark_dark_green: Sprite,
    not_played_yet_green: Sprite,
    not_played_yet_dark_green: Sprite,
    played_green: Sprite,
    played_dark_green: Sprite,
    close_fat: Sprite,
    close_white: Sprite,
    close_black: Sprite,
    close_map_preview: Sprite,
    color_picker: Sprite,
    change_recipe: Sprite,
    dropdown: Sprite,
    downloading: Sprite,
    downloading_white: Sprite,
    downloaded: Sprite,
    downloaded_white: Sprite,
    equipment_grid: Sprite,
    expand_dots: Sprite,
    expand_dots_white: Sprite,
    export: Sprite,
    import: Sprite,
    map: Sprite,
    map_exchange_string: Sprite,
    missing_mod_icon: Sprite,
    not_available: Sprite,
    play: Sprite,
    stop: Sprite,
    preset: Sprite,
    refresh: Sprite,
    reset: Sprite,
    reset_white: Sprite,
    shuffle: Sprite,
    station_name: Sprite,
    search_black: Sprite,
    search_white: Sprite,
    sync_mods: Sprite,
    trash: Sprite,
    trash_white: Sprite,
    copy: Sprite,
    reassign: Sprite,
    warning: Sprite,
    warning_white: Sprite,
    list_view: Sprite,
    grid_view: Sprite,
    reference_point: Sprite,
    mouse_cursor: Sprite,
    mod_dependency_arrow: Sprite,
    add: Sprite,
    clone: Sprite,
    go_to_arrow: Sprite,
    pause: Sprite,
    speed_down: Sprite,
    speed_up: Sprite,
    editor_speed_down: Sprite,
    editor_pause: Sprite,
    editor_play: Sprite,
    editor_speed_up: Sprite,
    tick_once: Sprite,
    tick_sixty: Sprite,
    tick_custom: Sprite,
    search_icon: Sprite,
    too_far: Sprite,
    shoot_cursor_green: Sprite,
    shoot_cursor_red: Sprite,
    electricity_icon: Sprite,
    fuel_icon: Sprite,
    ammo_icon: Sprite,
    fluid_icon: Sprite,
    warning_icon: Sprite,
    danger_icon: Sprite,
    destroyed_icon: Sprite,
    recharge_icon: Sprite,
    too_far_from_roboport_icon: Sprite,
    pump_cannot_connect_icon: Sprite,
    not_enough_repair_packs_icon: Sprite,
    not_enough_construction_robots_icon: Sprite,
    no_building_material_icon: Sprite,
    no_storage_space_icon: Sprite,
    electricity_icon_unplugged: Sprite,
    game_stopped_visualization: Sprite,
    health_bar_green_pip: Sprite,
    health_bar_yellow_pip: Sprite,
    health_bar_red_pip: Sprite,
    ghost_bar_pip: Sprite,
    bar_gray_pip: Sprite,
    shield_bar_pip: Sprite,
    hand: Sprite,
    hand_black: Sprite,
    entity_info_dark_background: Sprite,
    medium_gui_arrow: Sprite,
    small_gui_arrow: Sprite,
    light_medium: Sprite,
    light_small: Sprite,
    light_cone: Sprite,
    color_effect: Sprite,
    clock: Sprite,
    default_ammo_damage_modifier_icon: Sprite,
    default_gun_speed_modifier_icon: Sprite,
    default_turret_attack_modifier_icon: Sprite,
    hint_arrow_up: Sprite,
    hint_arrow_down: Sprite,
    hint_arrow_right: Sprite,
    hint_arrow_left: Sprite,
    fluid_indication_arrow: Sprite,
    fluid_indication_arrow_both_ways: Sprite,
    heat_exchange_indication: Sprite,
    indication_arrow: Sprite,
    rail_planner_indication_arrow: Sprite,
    rail_planner_indication_arrow_too_far: Sprite,
    rail_path_not_possible: Sprite,
    indication_line: Sprite,
    short_indication_line: Sprite,
    short_indication_line_green: Sprite,
    slot_icon_module: Sprite,
    slot_icon_module_black: Sprite,
    slot_icon_armor: Sprite,
    slot_icon_armor_black: Sprite,
    slot_icon_gun: Sprite,
    slot_icon_gun_black: Sprite,
    slot_icon_ammo: Sprite,
    slot_icon_ammo_black: Sprite,
    slot_icon_resource: Sprite,
    slot_icon_resource_black: Sprite,
    slot_icon_fuel: Sprite,
    slot_icon_fuel_black: Sprite,
    slot_icon_result: Sprite,
    slot_icon_result_black: Sprite,
    slot_icon_robot: Sprite,
    slot_icon_robot_black: Sprite,
    slot_icon_robot_material: Sprite,
    slot_icon_robot_material_black: Sprite,
    slot_icon_inserter_hand: Sprite,
    slot_icon_inserter_hand_black: Sprite,
    upgrade_blueprint: Sprite,
    slot: Sprite,
    equipment_slot: Sprite,
    equipment_collision: Sprite,
    battery: Sprite,
    green_circle: Sprite,
    green_dot: Sprite,
    robot_slot: Sprite,
    set_bar_slot: Sprite,
    missing_icon: Sprite,
    deconstruction_mark: Sprite,
    upgrade_mark: Sprite,
    confirm_slot: Sprite,
    export_slot: Sprite,
    import_slot: Sprite,
    none_editor_icon: Sprite,
    cable_editor_icon: Sprite,
    tile_editor_icon: Sprite,
    decorative_editor_icon: Sprite,
    resource_editor_icon: Sprite,
    entity_editor_icon: Sprite,
    item_editor_icon: Sprite,
    force_editor_icon: Sprite,
    clone_editor_icon: Sprite,
    scripting_editor_icon: Sprite,
    paint_bucket_icon: Sprite,
    surface_editor_icon: Sprite,
    time_editor_icon: Sprite,
    cliff_editor_icon: Sprite,
    brush_icon: Sprite,
    spray_icon: Sprite,
    cursor_icon: Sprite,
    area_icon: Sprite,
    line_icon: Sprite,
    variations_tool_icon: Sprite,
    lua_snippet_tool_icon: Sprite,
    editor_selection: Sprite,
    brush_square_shape: Sprite,
    brush_circle_shape: Sprite,
    player_force_icon: Sprite,
    neutral_force_icon: Sprite,
    enemy_force_icon: Sprite,
    nature_icon: Sprite,
    no_nature_icon: Sprite,
    multiplayer_waiting_icon: Sprite,
    spawn_flag: Sprite,
    questionmark: Sprite,
    copper_wire: Sprite,
    green_wire: Sprite,
    red_wire: Sprite,
    green_wire_hightlight: Sprite,
    red_wire_hightlight: Sprite,
    wire_shadow: Sprite,
    and_or: Sprite,
    left_arrow: Sprite,
    right_arrow: Sprite,
    down_arrow: Sprite,
    enter: Sprite,
    side_menu_blueprint_library_icon: Sprite,
    side_menu_production_icon: Sprite,
    side_menu_bonus_icon: Sprite,
    side_menu_tutorials_icon: Sprite,
    side_menu_train_icon: Sprite,
    side_menu_achievements_icon: Sprite,
    side_menu_menu_icon: Sprite,
    side_menu_map_icon: Sprite,
    side_menu_blueprint_library_hover_icon: Sprite,
    side_menu_production_hover_icon: Sprite,
    side_menu_bonus_hover_icon: Sprite,
    side_menu_tutorials_hover_icon: Sprite,
    side_menu_train_hover_icon: Sprite,
    side_menu_achievements_hover_icon: Sprite,
    side_menu_menu_hover_icon: Sprite,
    side_menu_map_hover_icon: Sprite,
    circuit_network_panel_black: Sprite,
    circuit_network_panel_white: Sprite,
    logistic_network_panel_black: Sprite,
    logistic_network_panel_white: Sprite,
    rename_icon_small_black: Sprite,
    rename_icon_small_white: Sprite,
    rename_icon_normal: Sprite,
    achievement_label_locked: Sprite,
    achievement_label_unlocked_off: Sprite,
    achievement_label_unlocked: Sprite,
    achievement_label_failed: Sprite,
    rail_signal_placement_indicator: Sprite,
    train_stop_placement_indicator: Sprite,
    placement_indicator_leg: Sprite,
    grey_rail_signal_placement_indicator: Sprite,
    grey_placement_indicator_leg: Sprite,
    logistic_radius_visualization: Sprite,
    construction_radius_visualization: Sprite,
    track_button: Sprite,
    show_logistics_network_in_map_view: Sprite,
    show_electric_network_in_map_view: Sprite,
    show_turret_range_in_map_view: Sprite,
    show_pollution_in_map_view: Sprite,
    show_train_station_names_in_map_view: Sprite,
    show_player_names_in_map_view: Sprite,
    show_tags_in_map_view: Sprite,
    show_worker_robots_in_map_view: Sprite,
    show_rail_signal_states_in_map_view: Sprite,
    show_recipe_icons_in_map_view: Sprite,
    show_logistics_network_in_map_view_black: Sprite,
    show_electric_network_in_map_view_black: Sprite,
    show_turret_range_in_map_view_black: Sprite,
    show_pollution_in_map_view_black: Sprite,
    show_train_station_names_in_map_view_black: Sprite,
    show_player_names_in_map_view_black: Sprite,
    show_tags_in_map_view_black: Sprite,
    show_worker_robots_in_map_view_black: Sprite,
    show_rail_signal_states_in_map_view_black: Sprite,
    show_recipe_icons_in_map_view_black: Sprite,
    train_stop_in_map_view: Sprite,
    train_stop_disabled_in_map_view: Sprite,
    train_stop_full_in_map_view: Sprite,
    custom_tag_in_map_view: Sprite,
    covered_chunk: Sprite,
    white_square: Sprite,
    white_mask: Sprite,
    favourite_server_icon: Sprite,
    crafting_machine_recipe_not_unlocked: Sprite,
    gps_map_icon: Sprite,
    custom_tag_icon: Sprite,
    underground_remove_belts: Sprite,
    underground_remove_pipes: Sprite,
    underground_pipe_connection: Sprite,
    ghost_cursor: Sprite,
    tile_ghost_cursor: Sprite,
    expand: Sprite,
    expand_dark: Sprite,
    collapse: Sprite,
    collapse_dark: Sprite,
    status_working: Sprite,
    status_not_working: Sprite,
    status_yellow: Sprite,
    gradient: Sprite,
    output_console_gradient: Sprite,
    select_icon_black: Sprite,
    select_icon_white: Sprite,
    notification: Sprite,
    alert_arrow: Sprite,
    technology_black: Sprite,
    technology_white: Sprite,
    inserter_stack_size_bonus_modifier_icon: Sprite,
    inserter_stack_size_bonus_modifier_constant: Option<Sprite>,
    stack_inserter_capacity_bonus_modifier_icon: Sprite,
    stack_inserter_capacity_bonus_modifier_constant: Option<Sprite>,
    laboratory_speed_modifier_icon: Sprite,
    laboratory_speed_modifier_constant: Option<Sprite>,
    character_logistic_slots_modifier_icon: Sprite,
    character_logistic_slots_modifier_constant: Option<Sprite>,
    character_logistic_trash_slots_modifier_icon: Sprite,
    character_logistic_trash_slots_modifier_constant: Option<Sprite>,
    maximum_following_robots_count_modifier_icon: Sprite,
    maximum_following_robots_count_modifier_constant: Option<Sprite>,
    worker_robot_speed_modifier_icon: Sprite,
    worker_robot_speed_modifier_constant: Option<Sprite>,
    worker_robot_storage_modifier_icon: Sprite,
    worker_robot_storage_modifier_constant: Option<Sprite>,
    ghost_time_to_live_modifier_icon: Sprite,
    ghost_time_to_live_modifier_constant: Option<Sprite>,
    turret_attack_modifier_icon: Sprite,
    turret_attack_modifier_constant: Option<Sprite>,
    ammo_damage_modifier_icon: Sprite,
    ammo_damage_modifier_constant: Option<Sprite>,
    give_item_modifier_icon: Sprite,
    give_item_modifier_constant: Option<Sprite>,
    gun_speed_modifier_icon: Sprite,
    gun_speed_modifier_constant: Option<Sprite>,
    unlock_recipe_modifier_icon: Sprite,
    unlock_recipe_modifier_constant: Option<Sprite>,
    character_crafting_speed_modifier_icon: Sprite,
    character_crafting_speed_modifier_constant: Option<Sprite>,
    character_mining_speed_modifier_icon: Sprite,
    character_mining_speed_modifier_constant: Option<Sprite>,
    character_running_speed_modifier_icon: Sprite,
    character_running_speed_modifier_constant: Option<Sprite>,
    character_build_distance_modifier_icon: Sprite,
    character_build_distance_modifier_constant: Option<Sprite>,
    character_item_drop_distance_modifier_icon: Sprite,
    character_item_drop_distance_modifier_constant: Option<Sprite>,
    character_reach_distance_modifier_icon: Sprite,
    character_reach_distance_modifier_constant: Option<Sprite>,
    character_resource_reach_distance_modifier_icon: Sprite,
    character_resource_reach_distance_modifier_constant: Option<Sprite>,
    character_item_pickup_distance_modifier_icon: Sprite,
    character_item_pickup_distance_modifier_constant: Option<Sprite>,
    character_loot_pickup_distance_modifier_icon: Sprite,
    character_loot_pickup_distance_modifier_constant: Option<Sprite>,
    character_inventory_slots_bonus_modifier_icon: Sprite,
    character_inventory_slots_bonus_modifier_constant: Option<Sprite>,
    deconstruction_time_to_live_modifier_icon: Sprite,
    deconstruction_time_to_live_modifier_constant: Option<Sprite>,
    max_failed_attempts_per_tick_per_construction_queue_modifier_icon: Sprite,
    max_failed_attempts_per_tick_per_construction_queue_modifier_constant: Option<Sprite>,
    max_successful_attempts_per_tick_per_construction_queue_modifier_icon: Sprite,
    max_successful_attempts_per_tick_per_construction_queue_modifier_constant: Option<Sprite>,
    character_health_bonus_modifier_icon: Sprite,
    character_health_bonus_modifier_constant: Option<Sprite>,
    mining_drill_productivity_bonus_modifier_icon: Sprite,
    mining_drill_productivity_bonus_modifier_constant: Option<Sprite>,
    train_braking_force_bonus_modifier_icon: Sprite,
    train_braking_force_bonus_modifier_constant: Option<Sprite>,
    zoom_to_world_enabled_modifier_icon: Sprite,
    zoom_to_world_enabled_modifier_constant: Option<Sprite>,
    zoom_to_world_ghost_building_enabled_modifier_icon: Sprite,
    zoom_to_world_ghost_building_enabled_modifier_constant: Option<Sprite>,
    zoom_to_world_blueprint_enabled_modifier_icon: Sprite,
    zoom_to_world_blueprint_enabled_modifier_constant: Option<Sprite>,
    zoom_to_world_deconstruction_planner_enabled_modifier_icon: Sprite,
    zoom_to_world_deconstruction_planner_enabled_modifier_constant: Option<Sprite>,
    zoom_to_world_upgrade_planner_enabled_modifier_icon: Sprite,
    zoom_to_world_upgrade_planner_enabled_modifier_constant: Option<Sprite>,
    zoom_to_world_selection_tool_enabled_modifier_icon: Sprite,
    zoom_to_world_selection_tool_enabled_modifier_constant: Option<Sprite>,
    worker_robot_battery_modifier_icon: Sprite,
    worker_robot_battery_modifier_constant: Option<Sprite>,
    laboratory_productivity_modifier_icon: Sprite,
    laboratory_productivity_modifier_constant: Option<Sprite>,
    follower_robot_lifetime_modifier_icon: Sprite,
    follower_robot_lifetime_modifier_constant: Option<Sprite>,
    artillery_range_modifier_icon: Sprite,
    artillery_range_modifier_constant: Option<Sprite>,
    nothing_modifier_icon: Sprite,
    nothing_modifier_constant: Option<Sprite>,
    character_additional_mining_categories_modifier_icon: Sprite,
    character_additional_mining_categories_modifier_constant: Option<Sprite>,
    character_logistic_requests_modifier_icon: Sprite,
    character_logistic_requests_modifier_constant: Option<Sprite>,
}

#[derive(Debug)]
pub struct UtilitySpritesCursorBox {
    regular: Vec<BoxSpecification>,
    not_allowed: Vec<BoxSpecification>,
    copy: Vec<BoxSpecification>,
    electricity: Vec<BoxSpecification>,
    logistics: Vec<BoxSpecification>,
    pair: Vec<BoxSpecification>,
    train_visualization: Vec<BoxSpecification>,
    blueprint_snap_rectangle: Vec<BoxSpecification>
}
