[package]
name = "factorio-lib-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorio-lib-rs-derive = { path = "./factorio-lib-rs-derive" }
mlua = { git = "https://github.com/JohnTheCoolingFan/factorio-mlua", features = ["serialize"] }
lexical-sort = "0.3.1"
zip = "0.5"
thiserror = "1.0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
semver = { version = "1.0", features = ["serde"] }
itertools = "0.10.1"
regex = "1.5.4"
once_cell = "1.8.0"
rust-ini = "0.17"
strum = { version = "0.22", features = ["derive"] }
strum_macros = "0.22"
