use strum_macros::{EnumString, AsRefStr};

/// Enum for all Prototype types available in the game
#[derive(Debug, Hash, Eq, PartialEq, Clone, Copy, EnumString, AsRefStr)]
#[strum(serialize_all = "kebab-case")]
pub enum PrototypeType {
    // All prototypes
    #[strum(serialize = "ambient-sound")]
    AmbientSoundPrototype,
    #[strum(serialize = "animation")]
    AnimationPrototype,
    EditorController,
    Font,
    GodController,
    MapGenPresets,
    MapSettings,
    MouseCursor,
    #[strum(serialize = "sound")]
    SoundPrototype,
    SpectatorController,
    #[strum(serialize = "sprite")]
    SpritePrototype,
    TileEffect,
    TipsAndTricksItemCategory,
    TriggerTargetType,
    WindSound,
    Achievement,
    BuildEntityAchievement,
    #[strum(serialize = "combat-robot-count")]
    CombatRobotCountAchievement,
    ConstructWithRobotsAchievement,
    DeconstructWithRobotsAchievement,
    DeliverByRobotsAchievement,
    DontBuildEntityAchievement,
    DontCraftManuallyAchievement,
    DontUseEntityInEnergyProductionAchievement,
    FinishTheGameAchievement,
    GroupAttackAchievement,
    KillAchievement,
    PlayerDamagedAchievement,
    ProduceAchievement,
    ProducePerHourAchievement,
    ResearchAchievement,
    TrainPathAchievement,
    AmmoCategory,
    AutoplaceControl,
    CustomInput,
    DamageType,
    #[strum(serialize = "optimized-decorative")]
    Decorative,
    Arrow,
    ArtilleryFlare,
    ArtilleryProjectile,
    Beam,
    CharacterCorpse,
    Cliff,
    #[strum(serialize = "corpse")]
    CorpsePrototype,
    RailRemnants,
    DeconstructibleTileProxy,
    EntityGhost,
    Accumulator,
    ArtilleryTurret,
    Beacon,
    Boiler,
    BurnerGenerator,
    Character,
    ArithmeticCombinator,
    DeciderCombinator,
    ConstantCombinator,
    Container,
    LogisticContainer,
    InfinityContainer,
    AssemblingMachine,
    RocketSilo,
    Furnace,
    ElectricEnergyInterface,
    ElectricPole,
    EnemySpawner,
    Fish,
    CombatRobot,
    ConstructionRobot,
    LogisticRobot,
    Gate,
    Generator,
    HeatInterface,
    HeatPipe,
    Inserter,
    Lab,
    Lamp,
    LandMine,
    LinkedContainer,
    Market,
    MiningDrill,
    OffshorePump,
    Pipe,
    InfinityPipe,
    PipeToGround,
    PlayerPort,
    PowerSwitch,
    ProgrammableSpeaker,
    Pump,
    Radar,
    CurvedRail,
    StraightRail,
    RailChainSignal,
    RailSignal,
    Reactor,
    Roboport,
    SimpleEntity,
    SimpleEntityWithOwner,
    SimpleEntityWithForce,
    SolarPanel,
    SpiderLeg,
    StorageTank,
    TrainStop,
    LinkedBelt,
    #[strum(serialize = "loader-1x1")]
    Loader1x1,
    #[strum(serialize = "loader")]
    Loader1x2,
    Splitter,
    TransportBelt,
    UndergroundBelt,
    Tree,
    #[strum(serialize = "turret")]
    Turret,
    AmmoTurret,
    ElectricTurret,
    FluidTurret,
    Unit,
    Car,
    ArtilleryWagon,
    CargoWagon,
    FluidWagon,
    Locomotive,
    SpiderVehicle,
    Wall,
    Explosion,
    FlameThrowerExplosion,
    FireFlame,
    #[strum(serialize = "stream")]
    FluidStream,
    FlyingText,
    #[strum(serialize = "highlight-box")]
    HighlightBoxEntity,
    ItemEntity,
    ItemRequestProxy,
    ParticleSource,
    Projectile,
    #[strum(serialize = "resource")]
    ResourceEntity,
    RocketSiloRocket,
    RocketSiloRocketShadow,
    SmokeWithTrigger,
    SpeechBubble,
    Sticker,
    TileGhost,
    ActiveDefenseEquipment,
    BatteryEquipment,
    BeltImmunityEquipment,
    EnergyShieldEquipment,
    GeneratorEquipment,
    MovementBonusEquipment,
    NightVisionEquipment,
    RoboportEquipment,
    SolarPanelEquipment,
    EquipmentCategory,
    EquipmentGrid,
    Fluid,
    FuelCategory,
    GuiStyle,
    #[strum(serialize = "item")]
    ItemPrototype,
    #[strum(serialize = "ammo")]
    AmmoItem,
    Capsule,
    Gun,
    ItemWithEntityData,
    ItemWithLabel,
    ItemWithInventory,
    BlueprintBook,
    ItemWithTags,
    #[strum(serialize = "selection-tool")]
    SelectionToolPrototype,
    BlueprintItem,
    CopyPasteTool,
    DeconstructionItem,
    UpgradeItem,
    Module,
    RailPlanner,
    SpidertronRemote,
    Tool,
    Armor,
    RepairTool,
    ItemGroup,
    #[strum(serialize = "item-subgroup")]
    ItemSubGroup,
    ModuleCategory,
    #[strum(serialize = "noise-expression")]
    NamedNoiseExpression,
    NoiseLayer,
    #[strum(serialize = "optimized-particle")]
    Particle,
    Recipe,
    RecipeCategory,
    ResourceCategory,
    Shortcut,
    Technology,
    Tile,
    TipsAndTricksItem,
    TrivialSmoke,
    Tutorial,
    UtilityConstants,
    UtilitySounds,
    UtilitySprites,
    VirtualSignal,
    // Mod setting prototypes
    BoolSetting,
    IntSetting,
    DoubleSetting,
    StringSetting
}
